
services:
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    command: start --optimized
    # command: start-dev
    # usar start-dev para desarrollo en lugar de start --optimized
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT:-true}
      - KC_HTTP_ENABLED=true
      - JAVA_OPTS=${JAVA_OPTS}
      - VIRTUAL_HOST=${KC_HOSTNAME}
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=${KC_HOSTNAME}
      - LETSENCRYPT_EMAIL=admin@${KC_HOSTNAME}
    networks:
      - sigicnetwork


volumes:
  keycloak_data:

networks:
  sigicnetwork:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1360"