
services:
  keycloak:
    image: ghcr.io/centrogeo/sigic-keycloak/keycloak-develop:${KEYCLOAK_TAG:-develop}
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    command: start --optimized
    # command: start-dev
    # usar start-dev para desarrollo en lugar de start --optimized
    restart: unless-stopped
    expose:
      - "8080"
    ports:
      - "8080:8080" 
    environment:
      - KC_DB=postgres
      - KC_DB_URL_HOST=${KC_DB_URL_HOST}
      - KC_DB_URL_DATABASE=${KC_DB_URL_DATABASE}
      - KC_DB_USERNAME=${KC_DB_USERNAME}
      - KC_DB_PASSWORD=${KC_DB_PASSWORD}
      - KC_HOSTNAME=${KC_HOSTNAME}
      - KC_PROXY_HEADERS=xforwarded
      - KC_HOSTNAME_STRICT=${KC_HOSTNAME_STRICT}
      - KC_HTTP_ENABLED=true
      - JAVA_OPTS=${JAVA_OPTS}
      - VIRTUAL_HOST=${KC_HOSTNAME}
      - VIRTUAL_PORT=8080
    networks:
      - keycloaknet

networks:
  keycloaknet:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: "1360"